## LIBRARY IMPORT

In [1]:
import pandas as pd
import numpy as np
import os
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression

C:\Users\srija\Anaconda3\lib\site-packages\sklearn\utils\__init__.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Sequence
C:\Users\srija\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:18: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Iterable
C:\Users\srija\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping, namedtuple, defaultdict, Sequence


## READING FILES

In [2]:
train_reviews = []
for line in open('../movie-sentiment-analysis/aclImdb/movie_data/full_train.txt','r',encoding='utf-8'):
    train_reviews.append(line.strip())
test_reviews = []
for line in open('../movie-sentiment-analysis/aclImdb/movie_data/full_test.txt','r',encoding='utf-8'):
    test_reviews.append(line.strip())

## CLEANING AND PROCESSING

In [3]:
no_space = re.compile("(\.)|(\;)|(\:)|(\!)|(\')|(\?)|(\,)|(\")|(\()|(\))|(\[)|(\])|(\d+)")
with_space = re.compile("(<br\s*/><br\s*/>)|(\-)|(\/)")
def cleaningandprocessing(reviews):
    reviews = [no_space.sub("",line.lower()) for line in reviews]
    reviews = [with_space.sub(" ",line) for line in reviews]
    return reviews
clean_train_reviews = cleaningandprocessing(train_reviews)
clean_test_reviews = cleaningandprocessing(test_reviews)

## USING NGRAMS

In [4]:
ngram_vectorizer = CountVectorizer(binary=True, ngram_range=(1, 2))
ngram_vectorizer.fit(clean_train_reviews)
X_train = ngram_vectorizer.transform(clean_train_reviews)
X_test = ngram_vectorizer.transform(clean_test_reviews)
target = [1 if i <12500 else 0 for i in range(25000)]
x_train, x_test, y_train, y_test = train_test_split(X_train, target, test_size=0.8, random_state=42)

In [5]:
for c in [0.01,0.05,0.1,0.5,1]:
    lr = LogisticRegression(C=c)
    lr.fit(x_train, y_train)
    print("For: ", c)
    print("\n")
    print(accuracy_score(y_test, lr.predict(x_test)))
    print("\n")
    print(confusion_matrix(y_test, lr.predict(x_test)))
    print("\n")
    print(classification_report(y_test, lr.predict(x_test)))
    print("\n\n")

For:  0.01


0.8578


[[8465 1497]
 [1347 8691]]


             precision    recall  f1-score   support

          0       0.86      0.85      0.86      9962
          1       0.85      0.87      0.86     10038

avg / total       0.86      0.86      0.86     20000




For:  0.05


0.8655


[[8557 1405]
 [1285 8753]]


             precision    recall  f1-score   support

          0       0.87      0.86      0.86      9962
          1       0.86      0.87      0.87     10038

avg / total       0.87      0.87      0.87     20000




For:  0.1


0.86545


[[8561 1401]
 [1290 8748]]


             precision    recall  f1-score   support

          0       0.87      0.86      0.86      9962
          1       0.86      0.87      0.87     10038

avg / total       0.87      0.87      0.87     20000




For:  0.5


0.86475


[[8559 1403]
 [1302 8736]]


             precision    recall  f1-score   support

          0       0.87      0.86      0.86      9962
          1       0.86      0.87   

### AT C = 0.05 ACCURACY SCORE IS 86.55

In [6]:
final_model = LogisticRegression(C=0.05)
final_model.fit(X_train, target)
print(accuracy_score(target, final_model.predict(X_test)))
print("\n")
print(confusion_matrix(target, final_model.predict(X_test)))
print("\n")
print(classification_report(target,final_model.predict(X_test)))

0.8976


[[11142  1358]
 [ 1202 11298]]


             precision    recall  f1-score   support

          0       0.90      0.89      0.90     12500
          1       0.89      0.90      0.90     12500

avg / total       0.90      0.90      0.90     25000



### FINAL MODEL ACCURACY SCORE IS 89.76 CLOSURE TO 90%