## LIBRARY IMPORT

In [1]:
import pandas as pd
import numpy as np
import os
import re

## READING FILES

In [2]:
train_reviews = []
for line in open('../movie-sentiment-analysis/aclImdb/movie_data/full_train.txt','r',encoding='utf-8'):
    train_reviews.append(line.strip())

In [3]:
test_reviews = []
for line in open('../movie-sentiment-analysis/aclImdb/movie_data/full_test.txt','r',encoding='utf-8'):
    test_reviews.append(line.strip())

## CLEANING AND PROCESSING

In [4]:
no_space = re.compile("(\.)|(\;)|(\:)|(\!)|(\')|(\?)|(\,)|(\")|(\()|(\))|(\[)|(\])|(\d+)")
with_space = re.compile("(<br\s*/><br\s*/>)|(\-)|(\/)")
def cleaningandprocessing(reviews):
    reviews = [no_space.sub("",line.lower()) for line in reviews]
    reviews = [with_space.sub(" ",line) for line in reviews]
    return reviews
clean_train_reviews = cleaningandprocessing(train_reviews)
clean_test_reviews = cleaningandprocessing(test_reviews)

## STEMMED DATA

In [5]:
def get_stemmed_text(corpus):
    from nltk.stem.porter import PorterStemmer
    stemmer = PorterStemmer()
    return [' '.join([stemmer.stem(word) for word in review.split()]) for review in corpus]
stemmed_reviews_train = get_stemmed_text(clean_train_reviews)
stemmed_reviews_test = get_stemmed_text(clean_test_reviews)

C:\Users\srija\Anaconda3\lib\site-packages\sklearn\feature_extraction\dict_vectorizer.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping


In [6]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression

In [8]:
cv = CountVectorizer(binary=True)
cv.fit(stemmed_reviews_train)
X_train = cv.transform(stemmed_reviews_train)
X_test = cv.transform(stemmed_reviews_test)
target = [1 if i <12500 else 0 for i in range(25000)]
x_train, x_test, y_train, y_test = train_test_split(X_train, target, test_size=0.8, random_state=42)

In [9]:
for c in [0.01,0.05,0.1,0.25,0.5,1]:
    lr = LogisticRegression(C=c)
    lr.fit(x_train, y_train)
    print("For: ", c)
    print("\n")
    print(accuracy_score(y_test, lr.predict(x_test)))
    print("\n")
    print(confusion_matrix(y_test, lr.predict(x_test)))
    print("\n")
    print(classification_report(y_test, lr.predict(x_test)))
    print("\n\n")

For:  0.01


0.8503


[[8399 1563]
 [1431 8607]]


             precision    recall  f1-score   support

          0       0.85      0.84      0.85      9962
          1       0.85      0.86      0.85     10038

avg / total       0.85      0.85      0.85     20000




For:  0.05


0.8579


[[8483 1479]
 [1363 8675]]


             precision    recall  f1-score   support

          0       0.86      0.85      0.86      9962
          1       0.85      0.86      0.86     10038

avg / total       0.86      0.86      0.86     20000




For:  0.1


0.85685


[[8475 1487]
 [1376 8662]]


             precision    recall  f1-score   support

          0       0.86      0.85      0.86      9962
          1       0.85      0.86      0.86     10038

avg / total       0.86      0.86      0.86     20000




For:  0.25


0.8544


[[8465 1497]
 [1415 8623]]


             precision    recall  f1-score   support

          0       0.86      0.85      0.85      9962
          1       0.85      0.86   

### AT C = 0.05 ACCURACY SCORE IS 85.79