## IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import os 
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.svm import LinearSVC

## READING FILES

In [4]:
train_review =[]
for line in open('../movie-sentiment-analysis/aclImdb/movie_data/full_train.txt','r',encoding='utf-8'):
    train_review.append(line.strip())

In [5]:
test_review=[]
for line in open('../movie-sentiment-analysis/aclImdb/movie_data/full_test.txt','r',encoding='utf-8'):
    test_review.append(line.strip())

## CLEANING AND PREPROCESS

In [6]:
no_space = re.compile("(\.)|(\;)|(\:)|(\!)|(\')|(\?)|(\,)|(\")|(\()|(\))|(\[)|(\])|(\d+)")
with_space = re.compile("(<br\s*/><br\s*/>)|(\-)|(\/)")
def cleaningandprocessing(reviews):
    reviews = [no_space.sub("",line.lower()) for line in reviews]
    reviews = [with_space.sub(" ",line) for line in reviews]
    return reviews
clean_train_reviews = cleaningandprocessing(train_review)
clean_test_reviews = cleaningandprocessing(test_review)

## USING NGRAM VECTORIZER

In [7]:
train_test_splitVectorizer(binary=True, ngram_range=(1,2))
cv.fit(clean_train_reviews)
X_train = cv.transform(clean_train_reviews)
X_test = cv.transform(clean_test_reviews)
target = [1 if i <12500 else 0 for i in range(25000)]

In [8]:
x_train, x_test, y_train, y_test = train_test_split(X_train, target, test_size=0.8, random_state=42)

In [9]:
for c in [0.01,0.05,0.1,0.25,0.5,1]:
    s = LinearSVC(C=c)
    s.fit(x_train, y_train)
    print("For: ", c)
    print("\n")
    print(accuracy_score(y_test, s.predict(x_test)))
    print("\n")
    print(confusion_matrix(y_test, s.predict(x_test)))
    print("\n")
    print(classification_report(y_test, s.predict(x_test)))
    print("\n\n")

For:  0.01


0.8643


[[8556 1406]
 [1308 8730]]


             precision    recall  f1-score   support

          0       0.87      0.86      0.86      9962
          1       0.86      0.87      0.87     10038

avg / total       0.86      0.86      0.86     20000




For:  0.05


0.86165


[[8532 1430]
 [1337 8701]]


             precision    recall  f1-score   support

          0       0.86      0.86      0.86      9962
          1       0.86      0.87      0.86     10038

avg / total       0.86      0.86      0.86     20000




For:  0.1


0.8599


[[8519 1443]
 [1359 8679]]


             precision    recall  f1-score   support

          0       0.86      0.86      0.86      9962
          1       0.86      0.86      0.86     10038

avg / total       0.86      0.86      0.86     20000




For:  0.25


0.8589


[[8510 1452]
 [1370 8668]]


             precision    recall  f1-score   support

          0       0.86      0.85      0.86      9962
          1       0.86      0.86   

### FOR C=0.01 ACCURACY SCORE IS MAX 86.43

In [10]:
final_model = LinearSVC(C=0.01)
final_model.fit(X_train, target)

LinearSVC(C=0.01, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [11]:
predictions1 = final_model.predict(X_test)
print("Accuracy score is: ",accuracy_score(target,predictions1))
print("\n")
print("Confusion matrix is: ", confusion_matrix(target, predictions1))
print("\n")
print("Classification matrix is: ",classification_report(target, predictions1))

Accuracy score is:  0.8976


Confusion matrix is:  [[11152  1348]
 [ 1212 11288]]


Classification matrix is:               precision    recall  f1-score   support

          0       0.90      0.89      0.90     12500
          1       0.89      0.90      0.90     12500

avg / total       0.90      0.90      0.90     25000



### FINAL MODEL ACCURACY SCORE IS 89.76