## IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import os 
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression

C:\Users\srija\Anaconda3\lib\site-packages\sklearn\utils\__init__.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Sequence
C:\Users\srija\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:18: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Iterable
C:\Users\srija\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping, namedtuple, defaultdict, Sequence


## READFILE

In [2]:
train_review =[]
for line in open('../movie-sentiment-analysis/aclImdb/movie_data/full_train.txt','r',encoding='utf-8'):
    train_review.append(line.strip())


In [3]:
test_review=[]
for line in open('../movie-sentiment-analysis/aclImdb/movie_data/full_test.txt','r',encoding='utf-8'):
    test_review.append(line.strip())

## CLEANING AND PROCESSING

In [4]:
no_space = re.compile("(\.)|(\;)|(\:)|(\!)|(\')|(\?)|(\,)|(\")|(\()|(\))|(\[)|(\])|(\d+)")
with_space = re.compile("(<br\s*/><br\s*/>)|(\-)|(\/)")
def cleaningandprocessing(reviews):
    reviews = [no_space.sub("",line.lower()) for line in reviews]
    reviews = [with_space.sub(" ",line) for line in reviews]
    return reviews
clean_train_reviews = cleaningandprocessing(train_review)
clean_test_reviews = cleaningandprocessing(test_review)

## USING WORD COUNT ANALYSIS

In [5]:
cv = CountVectorizer(binary=False)
cv.fit(clean_train_reviews)
X_train = cv.transform(clean_train_reviews)
X_test = cv.transform(clean_test_reviews)

In [6]:
target = [1 if i <12500 else 0 for i in range(25000)]
x_train, x_test, y_train, y_test = train_test_split(X_train, target, test_size=0.8, random_state=42)

In [7]:
for c in [0.01,0.05,0.1,0.25,0.5,1]:
    lr = LogisticRegression(C=c)
    lr.fit(x_train, y_train)
    print("For: ", c)
    print("\n")
    print(accuracy_score(y_test, lr.predict(x_test)))
    print("\n")
    print(confusion_matrix(y_test, lr.predict(x_test)))
    print("\n")
    print(classification_report(y_test, lr.predict(x_test)))
    print("\n\n")

For:  0.01


0.8462


[[8371 1591]
 [1485 8553]]


             precision    recall  f1-score   support

          0       0.85      0.84      0.84      9962
          1       0.84      0.85      0.85     10038

avg / total       0.85      0.85      0.85     20000




For:  0.05


0.85785


[[8496 1466]
 [1377 8661]]


             precision    recall  f1-score   support

          0       0.86      0.85      0.86      9962
          1       0.86      0.86      0.86     10038

avg / total       0.86      0.86      0.86     20000




For:  0.1


0.857


[[8490 1472]
 [1388 8650]]


             precision    recall  f1-score   support

          0       0.86      0.85      0.86      9962
          1       0.85      0.86      0.86     10038

avg / total       0.86      0.86      0.86     20000




For:  0.25


0.85645


[[8469 1493]
 [1378 8660]]


             precision    recall  f1-score   support

          0       0.86      0.85      0.86      9962
          1       0.85      0.86   

### FOR C = 0.05 ACCURACY SCORE = 85.875

In [8]:
final_model = LogisticRegression(C=0.05)
final_model.fit(X_train, target)
predictions1 = final_model.predict(X_test)
print("Accuracy score is: ",accuracy_score(target,predictions1))
print("\n")
print("Confusion matrix is: ", confusion_matrix(target, predictions1))
print("\n")
print("Classification matrix is: ",classification_report(target, predictions1))

Accuracy score is:  0.88196


Confusion matrix is:  [[11033  1467]
 [ 1484 11016]]


Classification matrix is:               precision    recall  f1-score   support

          0       0.88      0.88      0.88     12500
          1       0.88      0.88      0.88     12500

avg / total       0.88      0.88      0.88     25000



### FINAL MODEL ACCURACY SCORE IS 88.196